version: '3.7'
services:
  mongo:
    image: mongo:4.2.6-bionic
    volumes:
      - mongo_volume:/data/db
    restart: always
  mongo-express:
    image: mongo-express
    ports:
      - 127.0.0.1:8081:8081
    restart: always
    depends_on: 
      - mongo
  backend:
    image: node:14.0.0-stretch
    restart: always
    working_dir: /app
    environment:
      - PORT=5000
    ports: 
      - 5000:5000
    entrypoint: npx nodemon ./server.js localhost 5000
    volumes: 
      - "./backend/node_modules:/app/node_modules"
      - "./backend:/app"
    depends_on: 
      - mongo
  frontend:
    build:
      context: ./frontend
    restart: on-failure
    working_dir: /app
    entrypoint: supervisord -c /etc/supervisor.conf
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - "./frontend:/app"
volumes:
  mongo_volume:
